#!/bin/bash

# Setup script to configure deployment prerequisites
# This script helps set up the environment for deploying to all three platforms

set -e

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

print_status() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_header() {
    echo -e "\n${YELLOW}=== $1 ===${NC}\n"
}

echo "=================================================="
echo "🔧 Pakistan Train Tracker - Deployment Setup"
echo "=================================================="

# 1. Check for required tools
print_header "Checking Required Tools"

# Check git
if command -v git &> /dev/null; then
    print_status "git installed: $(git --version)"
else
    print_error "git not found. Install from: https://git-scm.com"
    exit 1
fi

# Check Node.js
if command -v node &> /dev/null; then
    print_status "Node.js installed: $(node --version)"
else
    print_error "Node.js not found. Install from: https://nodejs.org"
    exit 1
fi

# Check npm
if command -v npm &> /dev/null; then
    print_status "npm installed: $(npm --version)"
else
    print_error "npm not found"
    exit 1
fi

# 2. Google Cloud Setup
print_header "Google Cloud Run Setup"

if command -v gcloud &> /dev/null; then
    print_status "gcloud CLI installed"
    read -p "Enter your Google Cloud Project ID: " GCP_PROJECT
    gcloud config set project $GCP_PROJECT
    print_status "Project set to: $GCP_PROJECT"
else
    print_error "gcloud CLI not found"
    echo "Install from: https://cloud.google.com/sdk/docs/install"
    echo "Then run: gcloud auth login"
fi

# 3. Oracle Cloud Setup
print_header "Oracle Cloud Setup"

read -p "Enter Oracle Cloud instance IP (default: 138.2.91.18): " ORACLE_IP
ORACLE_IP="${ORACLE_IP:-138.2.91.18}"

read -p "Enter Oracle Cloud SSH username (default: ubuntu): " ORACLE_USER
ORACLE_USER="${ORACLE_USER:-ubuntu}"

echo "Testing SSH connection to Oracle instance..."
if ssh -o ConnectTimeout=5 $ORACLE_USER@$ORACLE_IP "echo 'Connection OK'" &> /dev/null; then
    print_status "SSH connection to Oracle successful"
else
    print_error "Cannot connect to $ORACLE_USER@$ORACLE_IP"
    echo "Make sure:"
    echo "  1. SSH key is set up"
    echo "  2. Security rules allow SSH (port 22)"
    echo "  3. IP address is correct"
fi

# 4. Koyeb Setup
print_header "Koyeb Setup"

if command -v koyeb &> /dev/null; then
    print_status "koyeb CLI installed"
    if koyeb whoami &> /dev/null; then
        print_status "koyeb authenticated"
    else
        echo "Please login to Koyeb:"
        koyeb auth login
    fi
else
    print_error "koyeb CLI not found"
    echo "Install from: https://www.koyeb.com"
    echo "macOS: brew install koyeb/tap/koyeb"
fi

# 5. Update configuration files
print_header "Updating Configuration"

# Create deploy config file
cat > "$(dirname "$0")/../.deploy-config" << EOF
# Deployment Configuration
# Auto-generated by setup-deployment.sh

GCP_PROJECT_ID=$GCP_PROJECT
ORACLE_IP=$ORACLE_IP
ORACLE_USER=$ORACLE_USER
KOYEB_APP=pakistan-train-tracker
KOYEB_REPO=github.com/arainz/pakistan-train-tracker
EOF

print_status "Deployment config saved to .deploy-config"

# 6. Summary
print_header "Setup Complete!"

echo "You're now ready to deploy!"
echo ""
echo "Quick start commands:"
echo ""
echo "  Deploy to all platforms:"
echo "    ./scripts/deploy-all.sh --all"
echo ""
echo "  Deploy to specific platform:"
echo "    ./scripts/deploy-all.sh --gcp"
echo "    ./scripts/deploy-all.sh --oracle"
echo "    ./scripts/deploy-all.sh --koyeb"
echo ""
echo "  View deployment guide:"
echo "    cat DEPLOYMENT_GUIDE.md"
echo ""

print_status "All checks passed! Ready for deployment."
