require_relative '../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../node_modules/@capacitor/app'
  pod 'CapacitorGeolocation', :path => '../../../node_modules/@capacitor/geolocation'
  pod 'CapacitorLocalNotifications', :path => '../../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorNetwork', :path => '../../../node_modules/@capacitor/network'
  pod 'CapacitorSplashScreen', :path => '../../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
  
  # Fix for Cordova header import issues with use_frameworks!
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # Disable User Script Sandboxing for CocoaPods
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
  
  # Fix for sandbox file-read-data errors - disable for main project too
  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |config_name, config_file|
      config_file.attributes['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      xcconfig_path = target.xcconfig_path(config_name)
      config_file.save_as(xcconfig_path)
    end
  end
end
